const test = require('tape')
const LRUCache = require('./LRUCache')

test('it evicts least recently used element when full', assert => {
  const cache = new LRUCache(2)
  cache.insert('A', 'letter A')
  cache.insert('B', 'letter B')
  assert.equal(cache.fetch('A'), 'letter A')
  assert.equal(cache.fetch('B'), 'letter B')
  assert.equal(cache.toString(), '[A:letter A],[B:letter B]')
  cache.insert('C', 'letter C')
  assert.equal(cache.fetch('A'), null)
  assert.equal(cache.toString(), '[B:letter B],[C:letter C]')
  cache.insert('D', 'letter D')
  assert.equal(cache.toString(), '[C:letter C],[D:letter D]')
  assert.equal(cache.fetch('C'), 'letter C')
  assert.equal(cache.toString(), '[D:letter D],[C:letter C]')
  assert.end()
})
