const test = require('tape')
const match = require('./BasicRegex')

test('it matches pattern without special chars', assert => {
  assert.equal(match('abc', 'abc'), true)
  assert.equal(match('', ''), true)
  assert.equal(match('abc', 'ab'), false)
  assert.equal(match('abc', 'a'), false)
  assert.equal(match('a', 'abc'), false)
  assert.equal(match('', 'abc'), false)
  assert.equal(match('abc', ''), false)
  assert.end()
})

test('it matches pattern with "." placeholder', assert => {
  assert.equal(match('abc', 'ab.'), true)
  assert.equal(match('abd', 'ab.'), true)
  assert.equal(match('axc', 'a.c'), true)
  assert.equal(match('abbc', 'a..c'), true)
  assert.equal(match('xbc', '.bc'), true)
  assert.equal(match('bc', '.bc'), false)
  assert.equal(match('abc', 'a.'), false)
  assert.end()
})

test('it matches pattern with "*" placeholder', assert => {
  assert.equal(match('abbc', 'ab*c'), true)
  assert.equal(match('abc', 'ax*.c'), true)
  assert.equal(match('abbc', 'ax*b*y*c'), true)
  assert.equal(match('bc', 'a*x*bc'), true)
  assert.equal(match('abc', 'ab*c*'), true)
  assert.equal(match('ab', 'ab*c*'), true)
  assert.equal(match('a', 'ab*c*'), true)
  assert.equal(match('ax', 'ab*c*d'), false)
  assert.equal(match('abbc', 'a.*c*'), true)
  assert.equal(match('', 'b*c*'), true)
  assert.equal(match('abx', 'ab*c*'), false)
  assert.end()
})
